### ISSUE TITLE
config - Deep merge semantics?

### ISSUE THREAD

**Issue by breerly** [uber-go/fx#213]
I don't see any docs or tests that describe how deep merge semantics work - are maps and objects merged, or is this just top-level? 

https://github.com/uber-go/fx/tree/master/config

**Comment by dmcaulay** [comment]
I have noticed an issue during my development. Here's the the example yaml:

```
# config/base.yaml

modules:
  rpc:
    name: mormont
    tchannel:
      listenOn: localhost
      advertise: true
      peerList: /etc/uber/hyperbahn/hosts.json
    inbounds:
      - tchannel:
          port: ${UBER_PORT_TCHANNEL:0}
    outbounds:
      - service: rosetta
        http:
          host: localhost
          port: 14797
          path: /thrift
      - services:
          - populous
          - safari
          - treatment
          - trident
        tchannel:
          host: 127.0.0.1
          port: ${UBER_PORT_TCHANNEL:0}
```

```
# config/development.yaml
modules:
  rpc:
    name: mormont
    tchannel:
      listenOn: localhost
      advertise: false
    inbounds:
      - tchannel:
          port: ${UBER_PORT_TCHANNEL:0}
    outbounds:
      - service: rosetta
        http:
          host: localhost
          port: 14797
          path: /thrift
      - services:
          - populous
          - safari
          - treatment
          - trident
        tchannel:
          host: 127.0.0.1
          port: ${UBER_PORT_TCHANNEL:0}
```

The issue that I'm seeing is that `advertise` is still `false` when I run in development. Other keys are updated properly:

```
# config/base.yaml

uconfig:
  enabled: true
```

```
# config/development.yaml

uconfig:
  enabled: true
  UConfigDir: mormont-config/crc_configs
```

I haven't had time to dig in and determine the root cause.
